scriptencoding utf-8
set encoding=utf-8
" Hello
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')
"

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
Plugin 'terryma/vim-multiple-cursors'

" Jedi autocompletion
Plugin 'davidhalter/jedi-vim'

"lightline
Plugin 'itchyny/lightline.vim'

" git viewer yay!
Plugin 'tpope/vim-fugitive.git'

" ultisnips
" Plugin 'SirVer/ultisnips.git'
" Narrow Regions - allows editing without screwing up your file
Plugin 'chrisbra/NrrwRgn.git'

" vim surrond
Plugin 'tpope/vim-surround.git'
" fuzzy searching with ctrlP
Plugin 'kien/ctrlp.vim'

" show marks for git differences
Plugin 'airblade/vim-gitgutter'
" autocomment stuff
Plugin 'tpope/vim-commentary'
" directory stuff
Plugin 'tpope/vim-vinegar'

" snippets for stuff
Bundle 'honza/vim-snippets'

" vim colorschemes
Plugin 'flazz/vim-colorschemes'
Bundle "daylerees/colour-schemes", { "rtp": "vim/" }

" flake8 for python
Plugin 'nvie/vim-flake8'

" go plugin
Plugin 'fatih/vim-go'
"
" multisearch
Bundle 'dyng/ctrlsf.vim.git'
" undo tree
Plugin 'mbbill/undotree'



" plugin from http://vim-scripts.org/vim/scripts.html
"Plugin 'L9'
" Git plugin not hosted on GitHub
"Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
"Plugin 'file:///home/gmarik/path/to/plugin'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
"Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Avoid a name conflict with L9
"Plugin 'user/L9', {'name': 'newL9'}

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line


" Mappings
" set qq  as escape
inoremap qq <Esc>
" highlight last inserted text
:nnoremap gV '[v`]
" disable arrow keys
:inoremap <Up> <nop>
:inoremap <Down> <nop>
:inoremap <Left> <nop>
:inoremap <Right> <nop>
" enable visual line movements
:nnoremap j gj
:nnoremap k gk
:nnoremap gj j
:nnoremap gk k
" switch tabs more easily
:nmap <tab> gt
:nmap <s-tab> gT
" stop the q: window coming up
:map q: :q



" look and feel
:set colorcolumn=80
:set laststatus=2
if !has('gui_running')
  set t_Co=256
  set t_ut=
endif
:let g:lightline = {
    \ 'colorscheme': 'wombat',
    \ }
:syntax enable
:set tabstop=4 shiftwidth=4 expandtab
" jump to multiple of tabstop
:set shiftround
" cool line numbering
:set number
":set relativenumber
nnoremap rtl :set relativenumber!<CR>

:colorscheme iceberg
:hi MatchParen ctermbg=67 
:highlight NonText ctermbg=none
:highlight Normal  ctermbg=none
" show me this when I have unwanted characters
exec "set listchars=tab:\u257c\u23e5,trail:\u02F3"
:set list

:highlight SpecialKey ctermfg=240   
:set wildmenu " visual autocomplete for command menu
:set wildmode=full
:set showcmd " show what I typed in normal mode
:set showmatch " show matching brackets
":set showbreak=<> " will put <> before wrapped lines
:set wrap linebreak nolist
:set hlsearch " highlight search matches
" change highlight color for search matches
:hi Search ctermbg=23 ctermfg=154
:hi Search term=bold

" completion menu colors
:highlight Pmenu ctermbg=23 ctermfg=7

" behaviour options
:let mapleader="\<Space>"
" yank/delete/put to/from system clipboard
vmap <Leader>y "+y
vmap <Leader>d "+d
nmap <Leader>y "+y
nmap <Leader>d "+d
nmap <Leader>p "+p
nmap <Leader>P "+P
vmap <Leader>p "+p
vmap <Leader>P "+P
:set autoindent

" backspace works as expected
" indent: delete autoindents
" eol: can delete line breaks
" start: can delete what I didn't insert this insert mode session
:set backspace=indent,eol,start

" j - remove comment
" r - comment new line if current line is commented
:set formatoptions+=rj

" this is one line

" notify if file change while editing
:set autoread
" save file if you call :make. Used by vim-go
:set autowrite

" netrw tree style
:let g:netrw_liststyle = 3

" search with smartcase
:set ignorecase
:set smartcase

" set to split below and to the right
:set splitbelow
:set splitright

" y, d, p will all use the plus register (copy/paste from system clipboard)
" :set clipboard=unnamedplus
" ycm disable tap
:let g:ycm_key_list_select_completion=[]
:let g:ycm_key_list_previous_completion=[]
:nmap <Leader>f <Plug>CtrlSFPrompt


" autodisappear docs
autocmd CursorMovedI * if pumvisible() == 0|pclose|endif
autocmd InsertLeave * if pumvisible() == 0|pclose|endif

"vim markdown
"let g:vim_markdown_folding_disabled=1


" Abbreviations
:abbreviate pyenv #!/usr/bin/env python
:abbreviate idebug import ipdb; ipdb.set_trace()
:abbreviate ifnm if __name__ == '__main__':<CR>

" Jedi settings
let g:jedi#smart_auto_mappings = 0


" golang settings
" show type info if cursor is on identifier
" let g:go_auto_type_info = 1
" commands
autocmd FileType go nmap <leader>t <Plug>(go-test)
" run test coverage checks. Remove highlights when rerun
autocmd FileType go nmap <Leader>c <Plug>(go-coverage-toggle)
" open alternate files in many ways
autocmd Filetype go command! -bang A call go#alternate#Switch(<bang>0, 'edit')
autocmd Filetype go command! -bang AV call go#alternate#Switch(<bang>0, 'vsplit')
autocmd Filetype go command! -bang AS call go#alternate#Switch(<bang>0, 'split')
autocmd Filetype go command! -bang AT call go#alternate#Switch(<bang>0, 'tabe')
" run :GoBuild or :GoTestCompile based on the go file
function! s:build_go_files()
  let l:file = expand('%')
  if l:file =~# '^\f\+_test\.go$'
    call go#cmd#Test(0, 1)
  elseif l:file =~# '^\f\+\.go$'
    call go#cmd#Build(0)
  endif
endfunction

autocmd FileType go nmap <leader>b :<C-u>call <SID>build_go_files()<CR>
autocmd FileType go nmap <leader>i :GoImports<CR>
autocmd FileType go nmap <leader>r :GoReferrers<CR>
autocmd FileType go nmap <leader>d :GoDescribe<CR>
autocmd FileType go nmap <Leader>I <Plug>CtrlSFPrompt
" automatically add import statements
let g:go_fmt_command = "goimports"

" syntax highlighting
let g:go_highlight_types = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
let g:go_auto_sameids = 1
